### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#13]
Justin named "metrics" as a reason for his rejection of AODVv2. Again, I'm not quite sure what exactly he meant by that, but we need to have a response ready.

**Comment by pv0** [comment]
It might have been the discussion about directionality of metrics. The current draft tries to optimise for the requested route, but I think I made some suggestions on trying to make metrics learned at other routers more accurate. It would require some big changes, the question is: is it necessary, or is what we have currently "good enough"?

**Comment by Lotterleben** [comment]
I'm inclined to say "good enough unless complained otherwise", buuuut would it make sense to mention your approach as possible future work in the experiment description section?

**Comment by charliep51** [comment]
Hello folks,

I agree with good enough.  I definitely think that metrics that actually 
measure something are to be preferred.  I have published a few examples, 
and can do more upon request if you have a favorite.

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
Charlie, nice idea! I agree that adding specific examples to the experiment section, I.e. saying something like "future experiments may explore the use of different metrics, such as x, y and z", would be really helpful. could you tell me which publications you think would be suitable? Unless somebody objects, I'd like to add references to those to the experiment section.

**Comment by Lotterleben** [comment]
Note: add paragraph to the end of 6.  Metrics that others may define other, non-cost metrics, but it's out of the scope of the draft to tell you how.

**Comment by charliep51** [comment]
Under the assumption that my pull request worked properly, this change is fine with me.  And thanks!

**Comment by Lotterleben** [comment]
@charliep51 I don't see any Pull Requests made by you, I think... :/

**Comment by Lotterleben** [comment]
@charliep51 , can we close this now or did you want to add anything?

**Comment by charliep51** [comment]
Hello Lotte,

If you want to make informative citations for the cost metric documents 
I submitted earlier this year let me know and I will send you the 
references.  Otherwise I am fine with closing the issue.

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
closed, but charlie wants to look for other cost metrics to cite for completeness :)
