### ISSUE TITLE
Ordering of processing operations

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#15]
Also mentioned by Justin, I believe in response to Jiazi's criticism:

> Some of the sections can be reorganized a bit to improve the readability.
> For example, with the current structure, the readers need to reach section
> 6.6 (Route discovery) before they can really touch the core function of the
> protocol.

**Comment by pv0** [comment]
I think you added a better overview of the protocol earlier in the draft though? Maybe this already addresses these comments? We can still look at the ordering though..?

**Comment by Lotterleben** [comment]
Hmm, true, that might help already? I don't think it's the same issue though...

**Comment by charliep51** [comment]
Hello folks,

If this is needed, the first step would be to propose a new outline for 
the draft.  Does anyone have a good idea about how to improve the 
overall outline of the draft?

Regards,
Charlie P.
