### ISSUE TITLE
RFC5444 wording

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#19]
In his review, Ulrich Herberg lists among his main points:

> - Ambiguities in RFC5444 format for messages: As described in my
detailed review, it's unclear to me whether or not some of the headers
should be added or not in the RFC5444 message. Also, some message
examples could be helpful in an appendix.

Regarding the header thing I think he's referring to this comment:

> UH> What does this mean? Can you add some text here? Are there any
other headers defined? (such as <msg-orig-addr>,
 <msg-hop-limit>, <msg-hop-count>, <msg-seq-num>)
> VM> Earlier in section 8 we state whether these fields are used. This version of the draft did not use any of those header fields. The newer version does use some and these are stated in this section in the new draft.
> LS> I’m not quite sure what kind of text you’re looking for here?
„Route Request Messages define two header fields, msg-type and msg-hop-limit, which are set as described in the following table: ...„ ?
>(In -15, no other headers were defined, but since we’ve reintroduced msg-hop-limit, that one’s part of this table now as well.)

(UH is ulrich, VM is vicky and LS is me.)

Regarding the examples in the appendix, do we want to add those? 
I'm assuming he's looking for something along the lines of [what OLSRv2 did](https://tools.ietf.org/html/rfc7181#appendix-D), so a very detailed description of a specific message and then the whole message bit by bit. Personally, I've found these to help only so much, because you've got to be really familiar with both RFC5444 and the specific message (and its values) that is being described before you can wrap your head around how it all goes together.

**Comment by pv0** [comment]
Well we do have a much better understanding of RFC5444 now, we could add some new message examples into an appendix. Personally I think the RFC5444 representation section should be enough. We could be extra specific that if not mentioned it he specific section, other header fields or flags are unused. I wouldn't want to end up re-writing a second RFC5444 section, like we were re-writing earlier sections with the pseudo code we removed.

**Comment by Lotterleben** [comment]
Exactly. Imo, the only value such an appendix adds is to give the reader the ability to check whether they understood our message description correctly. To achieve that, I think modeling one message type should be enough, since all message types are described in the same style... I.e. If we added a bit by bit illustration of one specific RREQ, the reader might use that to see if the would've built it the same way (optimizations aside) or whether they misunderstood the textual RREQ description/it was misleading. The more I think  about it, the more useful it seems to me actually... If the team wants me to, I'd volunteer to write such an appendix (and make it as short as I can ;) )

**Comment by charliep51** [comment]
Hello folks,

We already had that appendix, and it was taken out because of complaints 
from the WG.  If you want it back, I can send you the text.  I think it 
would be an excellent addition and was very sad to see it disappear.

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
The example from the Appendix you're referring to was incorrect, missing a description text (i.e. something like "this depicts a RREQ from origAddr abc::42 to targaddr C0::ffee with properties x, y and z.") and is deprecated as we significantly changed the message format since then. If we decide to do this, we'll have to write it from scratch. As I said, in that case I'll be happy to do that.

**Comment by charliep51** [comment]
Hello Lotte,

I didn't mean to say that the old Appendix could be used unmodified.  
And I don't in any way want to put any roadblock in your path by 
suggesting that I needed you to use the old Appendix.

I was mainly wondering why the idea was acceptable now and unacceptable 
back then.

One thing I know for sure is that it is very very easy to make mistakes 
in drawing RFC 5444 packet formats.  If the old Appendix could be in any 
way helpful, then so much the better.  But the packet diagrams, combined 
with the somewhat tedious bit fields of RFC 5444, make extraordinarily 
good places to put bugs.

Regards,
Charlie P.


On 5/30/2016 9:11 AM, Lotte Steenbrink wrote:
>
> The example from the Appendix you're referring to was incorrect, 
> missing a description text (i.e. something like "this depicts a RREQ 
> from origAddr abc::42 to targaddr C0::ffee with properties x, y and 
> z.") and is deprecated as we significantly changed the message format 
> since then. If we decide to do this, we'll have to write it from 
> scratch. As I said, in that case I'll be happy to do that.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Lotterleben/AODVv2-Draft/issues/19#issuecomment-222522001>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABbdvhDDphIsVz8FQBysaqeuaKbeUukuks5qGwwrgaJpZM4Igv6u>.
>

-- 
Regards,
Charlie P.

**Comment by Lotterleben** [comment]
Oooh okay. :) I agree about the bugs. I'm on the fence about re-including the Appendix, so I'll leave the decision to whoever has a stronger opinion on it...

**Comment by pv0** [comment]
I think the important issue to address is the comment: "it's unclear to me whether or not some of the headers should be added or not in the RFC5444 message." I would like the RFC5444 Representation section to be clear enough that we don't need to give example 5444 packets in an appendix. Maybe our problem is that the current text sums up the header field usage in the early paragraphs of the section, rather than stating the usage (or not) of header fields in the message specific sections.

**Comment by Lotterleben** [comment]
+1

**Comment by Lotterleben** [comment]
Hmm. Since RFC5444 requires the length of all addresses included in a message to be the same (i.e. you can't mix ipv4 and ipv6 addresses), we couldn't, say, have OrigAddr be (pure) IPv4 and TargAddr be IPv6. (You'd have to bypass this by mapping OrigAddr to IPv6, which doesn't cause as much extra payload as one would think since those addresses can usually be compressed nicely). While I was writing a disclaimer about that in section 9, I was wondering if mixing address types is desirable in general (i.e. if we should state this more prominently if it isn't just an RFC5444-related issue)?

**Comment by Lotterleben** [comment]
Even though #27 is merged I don't want to close this just yet, because I'm still not quite sure about the above comment regarding the mixing of IPv4/v6 addresses... Any input would be greatly appreciated :)

**Comment by charliep51** [comment]
Hello Lotte,

Since RFC 5444 requires all AODVv2 address elements to be of the same 
address family, I don't think it requires any additional specification 
in the AODVv2 document.  At most, you could put a sentence in section 9, 
perhaps after the sentence that begins:

"The addresses in an Address Block MAY appear in any order ..."

The sentence could be:

"RFC 5444 requires all AODVv2 address elements to be of the same address 
family."

Your choice :-)

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
Hi Charlie,
agreed, I was just wondering if this was an RFC5444-only case– i.e. if AODVv2 itself allows for IPv4 and IPv6 Addresses to be mixed, so if you were to implement your own packet format you could have an IPv4 OrigNode and an IPv6 TargNode. Then again that sounds a bit silly, so most likely I'm just confusing myself here... :D

**Comment by charliep51** [comment]
Hello Lotte,

There are protocols that allow for mixing address families-- it's not 
really a problem.  And in fact AODVv2 "should" allow for mixed 
families.  But we don't have the option if we are running over RFC5444.  
In the general case, if the AODVv2 protocol elements were mapped to a 
different protocol (or, say, directly on top of UDP) the representation 
of the message elements would have to be different.  The difference 
could include a bit somewhere to indicate address type.

I don't think we have to worry about that right now.

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
Allright, thanks for the explanation :)

**Comment by Lotterleben** [comment]
I think since @charliep51 resolved the reason I was hesistant to close this issue, it can be closed now, right? (feel free to reopen if you disagree ;) )

**Comment by charliep51** [comment]
I am good with closing the issue.
