### ISSUE TITLE
Missing constraints for parameters

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#20]
From ulrichs review:

> - Missing constraints for parameters: OLSRv2 details constraints on
all the parameters (such as minimum and maximum values), in particular
for those that can be changed during runtime. I think it would be a
good idea to include the same for AODVv2.

We decided against this, but it might be a good idea to dig through our e-mails and prepare a few sentences why we did so.

**Comment by charliep51** [comment]
Hello folks,

AODVv2 does not provide for changing these parameters at run time.

That would be a project for 2017, and has some interesting implications.

But just because OLSRv2 does something doesn't mean that AODVv2 has to 
do that.

Regards,
Charlie P.

**Comment by Lotterleben** [comment]
I no his main point was that we should include changing params at runtime but that parameters should have min/max constraints.
