### ISSUE TITLE
removal of timeouts

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#23]
Justin listed this as one of his points but I'm not quite sure which timeouts he's referring to.. 😕

**Comment by pv0** [comment]
This might be to do with confusion of 'are there timers or are you refreshing the state of anything before you then base a decision on the state' - and if there are timers, are they all listed somewhere, is there a table of running timers, etc...there were a few comments like that on MANET I think.

**Comment by charliep51** [comment]
Hello folks,

I guess we need to write to Justin to ask him what he was referring to, 
on this matter as well as one or two others.  Does anyone want to 
volunteer for this task?

Regards,
Charlie P.
