### ISSUE TITLE
Missing text in section 7.10.1

### ISSUE THREAD

**Issue by charliep51** [Lotterleben/AODVv2-Draft#29]
In section 7.10.1, the following bullet item seems to have lost some text:

 	   o  In all cases, if the time since LocalRoute.LastSeqNumUpdate	
	      exceeds MAX_SEQNUM_LIFETIME, LocalRoute.SeqNum must be set to

**Comment by Lotterleben** [comment]
Fixed in https://github.com/Lotterleben/AODVv2-Draft/pull/31
