### ISSUE TITLE
RREP plausibility check

### ISSUE THREAD

**Issue by Lotterleben** [Lotterleben/AODVv2-Draft#3]
-14 says

> 1.   If this RREP does not correspond to a RREQ generated or
>        regenerated in the last RREQ_WAIT_TIME, ignore for further
>        processing.

But it doesn't specify how to determine that the RREP corresponds to a RREQ (or not)– fix that.

**Comment by charliep51** [comment]
Hello folks,

It's O.K. to provide these details but if they were not provided the 
original specification would still be O.K.  In other words, "If this 
RREP does not correspond to a RREQ generated or regenerated in the last 
RREQ_WAIT_TIME, ignore for further processing" is pretty unambiguous and 
now we are being asked to write the program.

Regards,
Charlie P.
